[workspace]
resolver = "2"
members = [
    "crates/server",
]

[workspace.package]
version = "0.5.0"
edition = "2021"
homepage = "https://hyle.eu/"
repository = "https://github.com/Hyle-org/hyle/"
# licence = ""
