[workspace]
resolver = "2"
members = [
    "crates/server",
    "crates/ui",
]

[workspace.package]
version = "0.3.1"
edition = "2021"
homepage = "https://hyle.eu/"
repository = "https://github.com/Hyle-org/hyle/"
# licence = ""
