# Étape de build
FROM node:18-alpine AS build

# Installer pnpm
RUN npm install -g pnpm

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application
COPY web-react/package.json web-react/pnpm-lock.yaml ./

# Installer les dépendances
RUN pnpm install

# Copier le reste des fichiers de l'application
COPY web-react .

# Construire l'application
RUN pnpm run build

# Étape de production
FROM nginx:1.21.5-alpine AS production

# Copier les fichiers de build depuis l'étape de build
COPY --from=build /app/dist /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
