FROM rust:latest AS builder

RUN curl -L https://risczero.com/install | bash
RUN /root/.risc0/bin/rzup install

WORKDIR /app
COPY .cargo .cargo
COPY ./crates ./crates
COPY Cargo.toml . 
COPY Cargo.lock .

RUN cargo build -p server

# RUNNER
FROM rust:latest

WORKDIR /app

COPY --from=builder /app/target/debug/server ./

EXPOSE 3000

ENV RISC0_EXECUTOR=local

CMD ["./server"]

