[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
sdk = { git = "https://github.com/Hyle-org/hyle.git", package="hyle-contract-sdk" , branch = "main" }
hyllar = { git = "https://github.com/Hyle-org/hyle.git", package="hyllar", branch = "main"  }
hydentity = { git = "https://github.com/Hyle-org/hyle.git", package="hydentity", branch = "main"  }
amm = { git = "https://github.com/Hyle-org/hyle.git", package="amm", branch = "main"  }
hyle = { git = "https://github.com/Hyle-org/hyle.git", package="hyle", branch = "main"  }
bonsai_runner = { git = "https://github.com/Hyle-org/hyle.git", package="bonsai-runner", branch = "main"  }

# sdk = { path = "../../../hyle3/contract-sdk", package="hyle-contract-sdk"}
# hyllar = { path = "../../../hyle3/contracts/hyllar/contract", package="hyllar" }
# hydentity = { path = "../../../hyle3/contracts/hydentity/contract", package="hydentity" }
# amm = { path = "../../../hyle3/contracts/amm/contract", package="amm" }
# hyle = { path = "../../../hyle3", package="hyle" }

axum = "0.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tower-http = { version = "0.3", features = ["cors"] }
anyhow = "1.0.93"
reqwest = { version = "0.12.9", features = ["json"] }
hex = "0.4.3"

risc0-zkvm = { version = "1.1.3" }
borsh = "1.5.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.18"

