name: Frontend

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '23'

      - run: npm install -g pnpm

      - run: pnpm install

      - run: pnpm run build

